#' Regional parameters of the generalized extreme value distribution
#'
#' Contains parameters of the generalized extreme value distribution
#' fitted through the additive regional frequency analysis.
#'
#' @format A \code{data.frame} with 4 variables and 12 rows.
#'
#' \describe{
#' \item{Month}{Month}
#' \item{loc}{location parameter}
#' \item{scl}{scale parameter}
#' \item{shp}{shape parameter}
#' }
#'
#' @source Generated by the statistical simulation using the
#'         generalized extreme value distribution.
#'
#' @examples
#' data(parGEV)
"parGEV"
